from adapters.GameController import GameController
from adapters.GraphicGameController import GraphicGameController
from adapters.TrainingGameController import TrainingGameController

(GameController, GraphicGameController, TrainingGameController)
